/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Devices List
         * @description List available audio input devices.
         */
        get: operations["devices_list_api_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{device_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Devices Set
         * @description Set the audio input device.
         */
        put: operations["devices_set_api_devices__device_name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/focused-app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Focused App
         * @description The app that currently has focus, for tone match discovery. Null when unknown.
         */
        get: operations["focused_app_api_focused_app_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check backend health and status.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History List
         * @description List transcription history.
         *
         *     Args:
         *         limit: Maximum number of records to return
         *         offset: Number of records to skip (ignored if cursor is provided)
         *         search: Optional search query for full-text search
         *         cursor: Optional cursor for pagination (from previous response's next_cursor)
         *         fields: Optional comma-separated list of fields to include (e.g., "id,text,created_at")
         */
        get: operations["history_list_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Export Get
         * @description Export all transcription history.
         *
         *     Args:
         *         format: Export format (txt, json, csv, srt, vtt)
         *         include_metadata: Include metadata for JSON/CSV formats
         */
        get: operations["history_export_get_api_history_export_get"];
        put?: never;
        /**
         * History Export Post
         * @description Export transcription history with filtering options.
         *
         *     Supports filtering by date range, search query, or specific record IDs.
         */
        post: operations["history_export_post_api_history_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * History Import
         * @description Import transcriptions from a previously exported JSON file.
         *
         *     Args:
         *         data: The exported JSON data structure
         *         merge: If True, merge with existing history. If False, clear and replace.
         */
        post: operations["history_import_api_history_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Stats
         * @description Get history statistics.
         */
        get: operations["history_stats_api_history_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Get
         * @description Get a specific transcription record.
         */
        get: operations["history_get_api_history__record_id__get"];
        put?: never;
        post?: never;
        /**
         * History Delete
         * @description Delete a transcription record.
         */
        delete: operations["history_delete_api_history__record_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models List
         * @description List available models and their info.
         */
        get: operations["models_list_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Cache Info
         * @description Get model cache information including disk usage.
         */
        get: operations["models_cache_info_api_models_cache_get"];
        put?: never;
        post?: never;
        /**
         * Models Cache Clear
         * @description Clear model cache.
         *
         *     Args:
         *         model_name: Specific model to clear, or None to clear all cached models
         */
        delete: operations["models_cache_clear_api_models_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/download/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Models Download Cancel
         * @description Cancel the current model download.
         */
        post: operations["models_download_cancel_api_models_download_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/download/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Download Status
         * @description Get current download progress or null if no active download.
         */
        get: operations["models_download_status_api_models_download_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/downloaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Downloaded
         * @description Get list of downloaded/cached models.
         */
        get: operations["models_downloaded_api_models_downloaded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Models Load
         * @description Load a model with download progress tracking.
         */
        post: operations["models_load_api_models_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Recommend
         * @description Get model recommendation based on hardware.
         */
        get: operations["models_recommend_api_models_recommend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models Types
         * @description Get available model types.
         */
        get: operations["models_types_api_models_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Models Unload
         * @description Unload the current model.
         */
        post: operations["models_unload_api_models_unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Models By Type
         * @description Get models of a specific type.
         */
        get: operations["models_by_type_api_models__model_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/processing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Processing Status
         * @description What each mode will do: readiness per mode plus the active provider id.
         */
        get: operations["processing_status_api_processing_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings Get
         * @description Get current settings.
         */
        get: operations["settings_get_api_settings_get"];
        /**
         * Settings Update
         * @description Update settings.
         *
         *     Top-level fields replace. ``None`` is filtered out. Nested groups
         *     (``default_tone``, ``providers``, ``hotkeys``) replace wholesale, ``[]`` clears a
         *     list, and ``""`` clears ``active_provider_id``.
         */
        put: operations["settings_update_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/provider-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings Provider Keys
         * @description Report which configured providers have a stored key, without the key values.
         */
        get: operations["settings_provider_keys_api_settings_provider_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/providers/{provider_id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Settings Provider Key Set
         * @description Store or clear the API key for a configured provider.
         *
         *     An empty ``key`` clears the entry. The key value is never returned or logged.
         */
        put: operations["settings_provider_key_set_api_settings_providers__provider_id__key_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch List
         * @description List all batch transcription jobs.
         */
        get: operations["batch_list_api_transcribe_batch_get"];
        put?: never;
        /**
         * Batch Create
         * @description Create a new batch transcription job.
         *
         *     Args:
         *         file_paths: List of paths to audio files to transcribe
         */
        post: operations["batch_create_api_transcribe_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/batch/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch Get
         * @description Get status of a batch transcription job.
         */
        get: operations["batch_get_api_transcribe_batch__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Batch Delete
         * @description Delete a batch transcription job.
         */
        delete: operations["batch_delete_api_transcribe_batch__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/batch/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Cancel
         * @description Cancel a batch transcription job.
         */
        post: operations["batch_cancel_api_transcribe_batch__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/batch/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Retry
         * @description Retry failed files in a batch job.
         *
         *     Args:
         *         body: Optional request body. ``file_ids`` selects specific files;
         *             omit it, or send an empty body, to retry all failed files.
         */
        post: operations["batch_retry_api_transcribe_batch__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Cancel
         * @description Cancel current recording without transcribing.
         */
        post: operations["transcribe_cancel_api_transcribe_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Start
         * @description Start recording audio.
         */
        post: operations["transcribe_start_api_transcribe_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transcribe/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Stop
         * @description Stop recording and transcribe.
         */
        post: operations["transcribe_stop_api_transcribe_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppMatch
         * @description One rule that ties a tone profile to an app identifier or a window title.
         */
        AppMatch: {
            /**
             * Field
             * @enum {string}
             */
            field: "app" | "title";
            /** Pattern */
            pattern: string;
        };
        /**
         * AppSettings
         * @description Application settings with validation.
         */
        AppSettings: {
            /**
             * @description Mode the primary hotkey records in
             * @default dictate
             */
            active_mode: components["schemas"]["ProcessingMode"];
            /**
             * Active Provider Id
             * @description Provider used by LLM modes. Empty means none, because the update endpoint filters None and cannot clear a nullable field.
             * @default
             */
            active_provider_id: string;
            /**
             * Always Show Indicator
             * @description Keep indicator visible when idle
             * @default true
             */
            always_show_indicator: boolean;
            /**
             * Auto Paste
             * @description Automatically paste after transcription
             * @default true
             */
            auto_paste: boolean;
            /**
             * Command Prompt
             * @description System prompt for command mode
             * @default The user will speak an instruction. Carry it out and output only the text to insert, with no explanation.
             */
            command_prompt: string;
            /**
             * Compute Type
             * @description Compute precision
             * @default float16
             */
            compute_type: string;
            /**
             * Custom Filler Words
             * @description Additional filler words to remove
             */
            custom_filler_words?: string[] | null;
            /**
             * Debug Logging
             * @description Enable verbose backend logging
             * @default false
             */
            debug_logging: boolean;
            /** @description Tone used when no profile matches */
            default_tone?: components["schemas"]["ToneProfile"];
            /**
             * Device
             * @description Device to run on (cuda/cpu)
             * @default cuda
             * @enum {string}
             */
            device: "cuda" | "cpu";
            /**
             * Device Name
             * @description Audio input device name
             */
            device_name?: string | null;
            /**
             * Enable Text Cleanup
             * @description Remove filler words from transcription
             * @default true
             */
            enable_text_cleanup: boolean;
            /**
             * Hotkeys
             * @description Global hotkey bindings
             */
            hotkeys?: components["schemas"]["HotkeyBinding"][];
            /**
             * Language
             * @description Language code or 'auto'
             * @default auto
             */
            language: string;
            /**
             * Live Auto Paste
             * @description Auto-paste live transcripts into active window
             * @default false
             */
            live_auto_paste: boolean;
            /**
             * Live Chunk Seconds
             * @description Interval in seconds between live transcription updates
             * @default 3
             */
            live_chunk_seconds: number;
            /**
             * Live Transcription
             * @description Enable real-time partial transcription while recording
             * @default false
             */
            live_transcription: boolean;
            /**
             * Model Name
             * @description Model name or HuggingFace repo ID
             * @default nvidia/parakeet-tdt-0.6b-v3
             */
            model_name: string;
            /**
             * Model Type
             * @description ASR model type
             * @default parakeet
             */
            model_type: string;
            /**
             * Providers
             * @description Configured OpenAI-compatible providers
             */
            providers?: components["schemas"]["LlmProvider"][];
            /**
             * Server Port
             * @description Backend server port
             * @default 8765
             */
            server_port: number;
            /**
             * Show Recording Indicator
             * @description Show recording overlay
             * @default true
             */
            show_recording_indicator: boolean;
            /**
             * Theme
             * @description UI theme name
             * @default default
             */
            theme: string;
            /**
             * Tone Profiles
             * @description Per-app tone profiles for write mode
             */
            tone_profiles?: components["schemas"]["ToneProfile"][];
        };
        /** BatchCreateRequest */
        BatchCreateRequest: {
            /** File Paths */
            file_paths: string[];
        };
        /** BatchProgressEvent */
        BatchProgressEvent: {
            /** Completed */
            completed: number;
            /** Current File */
            current_file: string | null;
            /** Current Index */
            current_index: number;
            /** Failed */
            failed: number;
            /**
             * File Status
             * @default null
             */
            file_status: ("pending" | "processing" | "completed" | "failed" | "skipped") | null;
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "completed" | "cancelled" | "failed";
            /** Total Files */
            total_files: number;
        };
        /** BatchRetryRequest */
        BatchRetryRequest: {
            /** File Ids */
            file_ids?: string[] | null;
        };
        /** ConnectedEvent */
        ConnectedEvent: {
            /** Model Loaded */
            model_loaded: boolean;
            /** State */
            state: string;
        };
        /** DownloadProgressEvent */
        DownloadProgressEvent: {
            /** Bytes Per Second */
            bytes_per_second: number;
            /** Download Id */
            download_id: string;
            /** Downloaded Bytes */
            downloaded_bytes: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Error Message */
            error_message: string | null;
            /** Estimated Remaining Seconds */
            estimated_remaining_seconds: number | null;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
            /** Progress Percent */
            progress_percent: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "downloading" | "completed" | "cancelled" | "error";
            /** Total Bytes */
            total_bytes: number;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /** Message */
            message: string;
        };
        /**
         * ExportFormat
         * @description Supported export formats.
         * @enum {string}
         */
        ExportFormat: "txt" | "json" | "csv" | "srt" | "vtt";
        /** ExportRequest */
        ExportRequest: {
            /** End Date */
            end_date?: string | null;
            format: components["schemas"]["ExportFormat"];
            /**
             * Include Metadata
             * @default true
             */
            include_metadata: boolean;
            /** Record Ids */
            record_ids?: string[] | null;
            /** Search */
            search?: string | null;
            /** Start Date */
            start_date?: string | null;
        };
        /** FocusedAppResponse */
        FocusedAppResponse: {
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Gpu Available */
            gpu_available: boolean;
            /** Gpu Name */
            gpu_name: string | null;
            /** Gpu Vram Gb */
            gpu_vram_gb: number | null;
            /** Model Loaded */
            model_loaded: boolean;
            /** Model Name */
            model_name: string | null;
            /** State */
            state: string;
            /** Status */
            status: string;
        };
        /** HistoryListResponse */
        HistoryListResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /**
         * HotkeyBinding
         * @description A global chord. ``mode`` None records in ``active_mode`` at press time.
         */
        HotkeyBinding: {
            /** Accelerator */
            accelerator: string;
            mode?: components["schemas"]["ProcessingMode"] | null;
            /**
             * Trigger
             * @default toggle
             * @enum {string}
             */
            trigger: "toggle" | "push-to-talk";
        };
        /** ImportRequest */
        ImportRequest: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Merge
             * @default true
             */
            merge: boolean;
        };
        /** LiveTranscriptEvent */
        LiveTranscriptEvent: {
            /** Text */
            text: string;
        };
        /**
         * LlmProvider
         * @description One OpenAI-compatible chat endpoint. Credentials live in secrets.json, not here.
         */
        LlmProvider: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /** Id */
            id: string;
            /** @default local */
            kind: components["schemas"]["ProviderKind"];
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Timeout Seconds
             * @default 20
             */
            timeout_seconds: number;
        };
        /** ModeStatusResponse */
        ModeStatusResponse: {
            mode: components["schemas"]["ProcessingMode"];
            /** Ready */
            ready: boolean;
            /** Reason */
            reason: string | null;
        };
        /** ModelLoadRequest */
        ModelLoadRequest: {
            /** Compute Type */
            compute_type?: string | null;
            /** Device */
            device?: ("cuda" | "cpu") | null;
            /** Model Name */
            model_name: string;
            /** Model Type */
            model_type: string;
        };
        /**
         * ProcessingMode
         * @description How a transcript is processed before it is inserted.
         * @enum {string}
         */
        ProcessingMode: "write" | "command" | "dictate";
        /** ProcessingStatusResponse */
        ProcessingStatusResponse: {
            /** Modes */
            modes: components["schemas"]["ModeStatusResponse"][];
            /** Provider Id */
            provider_id: string;
        };
        /** ProviderKeyRequest */
        ProviderKeyRequest: {
            /** Key */
            key: string;
        };
        /** ProviderKeyResponse */
        ProviderKeyResponse: {
            /** Has Key */
            has_key: boolean;
            /** Provider Id */
            provider_id: string;
        };
        /**
         * ProviderKind
         * @description Transport family of an OpenAI-compatible chat provider.
         * @enum {string}
         */
        ProviderKind: "local" | "openai" | "groq" | "custom";
        /** SettingsUpdateRequest */
        SettingsUpdateRequest: {
            active_mode?: components["schemas"]["ProcessingMode"] | null;
            /** Active Provider Id */
            active_provider_id?: string | null;
            /** Always Show Indicator */
            always_show_indicator?: boolean | null;
            /** Auto Paste */
            auto_paste?: boolean | null;
            /** Command Prompt */
            command_prompt?: string | null;
            /** Compute Type */
            compute_type?: string | null;
            /** Custom Filler Words */
            custom_filler_words?: string[] | null;
            /** Debug Logging */
            debug_logging?: boolean | null;
            default_tone?: components["schemas"]["ToneProfile"] | null;
            /** Device */
            device?: ("cuda" | "cpu") | null;
            /** Device Name */
            device_name?: string | null;
            /** Enable Text Cleanup */
            enable_text_cleanup?: boolean | null;
            /** Hotkeys */
            hotkeys?: components["schemas"]["HotkeyBinding"][] | null;
            /** Language */
            language?: string | null;
            /** Live Auto Paste */
            live_auto_paste?: boolean | null;
            /** Live Chunk Seconds */
            live_chunk_seconds?: number | null;
            /** Live Transcription */
            live_transcription?: boolean | null;
            /** Model Name */
            model_name?: string | null;
            /** Model Type */
            model_type?: string | null;
            /** Providers */
            providers?: components["schemas"]["LlmProvider"][] | null;
            /** Server Port */
            server_port?: number | null;
            /** Show Recording Indicator */
            show_recording_indicator?: boolean | null;
            /** Theme */
            theme?: string | null;
            /** Tone Profiles */
            tone_profiles?: components["schemas"]["ToneProfile"][] | null;
        };
        /** SettingsUpdateResponse */
        SettingsUpdateResponse: {
            /** Reload Required */
            reload_required: boolean;
            settings?: components["schemas"]["AppSettings"] | null;
            /** Status */
            status: string;
        };
        /** StatusEvent */
        StatusEvent: {
            /** Recording */
            recording: boolean;
            /** State */
            state: string;
        };
        /**
         * ToneProfile
         * @description A rewrite tone used in write mode when one of its matches fires.
         */
        ToneProfile: {
            /** Matches */
            matches?: components["schemas"]["AppMatch"][];
            /** Name */
            name: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
        };
        /** TranscribeStartResponse */
        TranscribeStartResponse: {
            /** Status */
            status: string;
        };
        /** TranscribeStopRequest */
        TranscribeStopRequest: {
            /** Auto Paste */
            auto_paste?: boolean | null;
            /** Instruction */
            instruction?: string | null;
            /** Language */
            language?: string | null;
            mode?: components["schemas"]["ProcessingMode"] | null;
        };
        /** TranscribeStopResponse */
        TranscribeStopResponse: {
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Language */
            language: string | null;
            mode: components["schemas"]["ProcessingMode"];
            /** Model Used */
            model_used: string | null;
            /** Original Text */
            original_text?: string | null;
            /** Processing Error */
            processing_error?: string | null;
            /** Text */
            text: string;
        };
        /** TranscriptionEvent */
        TranscriptionEvent: {
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /**
             * Original Text
             * @default null
             */
            original_text: string | null;
            /**
             * Processing Error
             * @default null
             */
            processing_error: string | null;
            /** Text */
            text: string;
        };
        /** TranscriptionProgressEvent */
        TranscriptionProgressEvent: {
            /** Chunk Text */
            chunk_text: string;
            /** Current Chunk */
            current_chunk: number;
            /** Progress Percent */
            progress_percent: number;
            /** Total Chunks */
            total_chunks: number;
        };
        /** TranscriptionRecord */
        TranscriptionRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Is Ai Enhanced */
            is_ai_enhanced: boolean;
            /** Language */
            language: string | null;
            /** Model Used */
            model_used: string | null;
            /** Original Text */
            original_text: string | null;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    devices_list_api_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    devices_set_api_devices__device_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    focused_app_api_focused_app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FocusedAppResponse"] | null;
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    history_list_api_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
                cursor?: string | null;
                fields?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_export_get_api_history_export_get: {
        parameters: {
            query?: {
                format?: string;
                include_metadata?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_export_post_api_history_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_import_api_history_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_stats_api_history_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    history_get_api_history__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_delete_api_history__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_list_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_cache_info_api_models_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_cache_clear_api_models_cache_delete: {
        parameters: {
            query?: {
                model_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_download_cancel_api_models_download_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_download_status_api_models_download_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_downloaded_api_models_downloaded_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_load_api_models_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelLoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_recommend_api_models_recommend_get: {
        parameters: {
            query?: {
                needs_translation?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_types_api_models_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_unload_api_models_unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    models_by_type_api_models__model_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    processing_status_api_processing_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingStatusResponse"];
                };
            };
        };
    };
    settings_get_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    settings_update_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_provider_keys_api_settings_provider_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    settings_provider_key_set_api_settings_providers__provider_id__key_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_list_api_transcribe_batch_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    batch_create_api_transcribe_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_get_api_transcribe_batch__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_api_transcribe_batch__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_cancel_api_transcribe_batch__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_retry_api_transcribe_batch__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BatchRetryRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_cancel_api_transcribe_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    transcribe_start_api_transcribe_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeStartResponse"];
                };
            };
        };
    };
    transcribe_stop_api_transcribe_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeStopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeStopResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
